### PR TITLE
delete event collection if exists and seed data again

### PR DESCRIPTION
**Pull request by nishi-ai**
Purpose: update event data for development
Link Issue: [creating tab for FE](https://github.com/nishi-ai/softball-register-web/issues/47)

### CODE REVIEW

**Review by benevbright — COMMENTED** [review]
The code seems to have a mistake. 

It wouldn't create `events` collection when `events` collection is not present. 
We want it to create the collection.

**Review by benevbright — APPROVED** [review]
LGTM. 

Just double checking. `await db.collection("events").drop();` won't throw an error even if when there is no `events` collection? Then it should be fine.

**Comment by nishi-ai** [comment]
> 

no, I don't get any error🥸

**Review by benevbright — APPROVED** [review]
😎👍

**Pull request merged**
