### PR TITLE
deleted mongoose.connect and added Access-Control-Allow-Origin' header

### PR DESCRIPTION
**Pull request by nishi-ai**
added Access-Control-Allow-Origin' header
because of this error on the production
Screenshot 2021-08-14 at 11 37 45

### CODE REVIEW

**Comment by benevbright** [comment]
@nishi-ai I think the issue is not about the header but App seems to crash on the production. 
I think it crashes on the line `mongoose.connect`. It works fine on dev because dev doesn't go there `if`. 

The header issue is just by the fact that the server is down.

Could you just remove that line and test on the production?

**Comment by benevbright** [comment]
I guessed so because we haven't had this problem so far and we only added DB without touching the connection between the front-end and the node.js server.

**Review by benevbright — APPROVED** [review]
LGTM!

**Comment by nishi-ai** [comment]
works on the production!

**Comment by nishi-ai** [comment]
how can i test in db?

**Comment by benevbright** [comment]
Awesome 👍 quick fix!

**Comment by benevbright** [comment]
@nishi-ai You can connect to the production db like
```
mongosh mongodb+srv://root:supersecret@cluster0.ddfbs.mongodb.net
```
and you will need to switch to the `softball` db and check `players` collection.

mongosh manual:
https://docs.mongodb.com/mongodb-shell/run-commands/

**Comment by nishi-ai** [comment]
ok! the production db also works!

**Pull request merged**
